version: "3"

services:

  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ${APP_PATH}:/var/www/html
    environment:
      - ROOT_DIR=${DOCUMENT_ROOT}
      - PHP_FPM=php
    ports:
      - "8080:80"

  php:
    build:
      context: ./docker/php
      args:
        - php_version=${PHP_VERSION}
        - composer_version=${COMPOSER_VERSION}
        - user=${USER}
    volumes:
      - ${APP_PATH}:/var/www/html
      - ${SSH_AUTH_SOCK}:/ssh-auth.sock
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - SSH_AUTH_SOCK=/ssh-auth.sock

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"